-- CreateEnum
CREATE TYPE "public"."EventStatus" AS ENUM ('draft', 'published', 'live', 'completed', 'cancelled');

-- CreateEnum
CREATE TYPE "public"."LocationVisibility" AS ENUM ('immediate', 'confirmed_guests', '24_hours_before');

-- CreateEnum
CREATE TYPE "public"."GuestListVisibility" AS ENUM ('public', 'attendees_live', 'private');

-- CreateEnum
CREATE TYPE "public"."PricingModel" AS ENUM ('fixed_price', 'choose_your_price', 'donation_based', 'free_rsvp');

-- CreateEnum
CREATE TYPE "public"."PositionStatus" AS ENUM ('open', 'filled', 'closed');

-- CreateEnum
CREATE TYPE "public"."ApplicationStatus" AS ENUM ('pending', 'accepted', 'declined', 'withdrawn');

-- CreateTable
CREATE TABLE "public"."users" (
    "id" TEXT NOT NULL,
    "email" TEXT,
    "username" TEXT NOT NULL,
    "phone_number" TEXT,
    "is_phone_verified" BOOLEAN NOT NULL DEFAULT false,
    "hashed_password" TEXT,
    "profile_picture_url" TEXT,
    "bio" TEXT,
    "instagram_handle" TEXT,
    "personal_website_url" TEXT,
    "is_username_autogenerated" BOOLEAN NOT NULL DEFAULT true,
    "privacy_show_upcoming_events" BOOLEAN NOT NULL DEFAULT true,
    "privacy_show_past_events" BOOLEAN NOT NULL DEFAULT true,
    "privacy_past_events_include_hosted" BOOLEAN NOT NULL DEFAULT true,
    "privacy_past_events_include_collaborated" BOOLEAN NOT NULL DEFAULT true,
    "privacy_past_events_include_attended" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."events" (
    "id" TEXT NOT NULL,
    "host_user_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "cover_image_url" TEXT,
    "start_time" TIMESTAMP(3) NOT NULL,
    "end_time" TIMESTAMP(3) NOT NULL,
    "location_address" TEXT NOT NULL,
    "status" "public"."EventStatus" NOT NULL,
    "location_visibility" "public"."LocationVisibility" NOT NULL,
    "guest_list_visibility" "public"."GuestListVisibility" NOT NULL,
    "is_invite_only" BOOLEAN NOT NULL DEFAULT false,
    "max_capacity" INTEGER,
    "pricing_model" "public"."PricingModel" NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "price_fixed" DECIMAL(10,2),
    "price_min" DECIMAL(10,2),
    "price_suggested" DECIMAL(10,2),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."open_positions" (
    "id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "role_title" VARCHAR(30) NOT NULL,
    "description" TEXT,
    "profit_share_percentage" DECIMAL(5,2),
    "status" "public"."PositionStatus" NOT NULL,
    "filled_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "open_positions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."applications" (
    "id" TEXT NOT NULL,
    "position_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "message" TEXT,
    "status" "public"."ApplicationStatus" NOT NULL,
    "applied_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "accepted_collaboration_id" TEXT,

    CONSTRAINT "applications_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "public"."users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "public"."users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "users_phone_number_key" ON "public"."users"("phone_number");

-- CreateIndex
CREATE UNIQUE INDEX "applications_accepted_collaboration_id_key" ON "public"."applications"("accepted_collaboration_id");

-- CreateIndex
CREATE UNIQUE INDEX "applications_position_id_user_id_key" ON "public"."applications"("position_id", "user_id");

-- AddForeignKey
ALTER TABLE "public"."events" ADD CONSTRAINT "events_host_user_id_fkey" FOREIGN KEY ("host_user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."open_positions" ADD CONSTRAINT "open_positions_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."open_positions" ADD CONSTRAINT "open_positions_filled_by_user_id_fkey" FOREIGN KEY ("filled_by_user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."applications" ADD CONSTRAINT "applications_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "public"."open_positions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."applications" ADD CONSTRAINT "applications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
